### ISSUE TITLE
windows XP compatibility

### ISSUE THREAD

**Issue by llombard** [Koheron/laser-development-kit#88]
trying to run 
python interface.py
under windows XP with anaconda 2.2 and python 2.7 and required libraries raises the following error:
`C:\test\laser-development-kit>python interface.py
Traceback (most recent call last):
  File "interface.py", line 124, in <module>
    main()
  File "interface.py", line 108, in main
    ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
  File "C:\Anaconda\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Anaconda\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SetCurrentProcessExplicitAppUserModelID' not found`

**Comment by jeanminet** [comment]
Thanks for the info.
This should be solved by #89

**Comment by llombard** [comment]
yes it works. thanks a lot!
